<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-09T17:14:20 IST" name="Default suite" finished-at="2023-01-09T17:15:56 IST" duration-ms="95863">
    <groups>
      <group name="smoke">
        <method signature="LoginTest.InvalidNumberLogin()[pri:1, instance:flipkart.TestCases.LoginTest@293cde83]" name="InvalidNumberLogin" class="flipkart.TestCases.LoginTest"/>
        <method signature="LoginTest.ValidNumberLogin()[pri:2, instance:flipkart.TestCases.LoginTest@293cde83]" name="ValidNumberLogin" class="flipkart.TestCases.LoginTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2023-01-09T17:14:20 IST" name="Default test" finished-at="2023-01-09T17:15:56 IST" duration-ms="95863">
      <class name="flipkart.TestCases.LoginTest">
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:flipkart.TestCases.LoginTest@293cde83]" started-at="2023-01-09T17:14:20 IST" name="setup" finished-at="2023-01-09T17:15:08 IST" duration-ms="48057" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void flipkart.TestCases.LoginTest.InvalidNumberLogin() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="InvalidNumberLogin()[pri:1, instance:flipkart.TestCases.LoginTest@293cde83]" started-at="2023-01-09T17:15:08 IST" name="InvalidNumberLogin" finished-at="2023-01-09T17:15:08 IST" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidNumberLogin -->
        <test-method is-config="true" signature="status(org.testng.ITestResult)[pri:0, instance:flipkart.TestCases.LoginTest@293cde83]" started-at="2023-01-09T17:15:08 IST" name="status" finished-at="2023-01-09T17:15:08 IST" duration-ms="272" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=InvalidNumberLogin status=SUCCESS method=LoginTest.InvalidNumberLogin()[pri:1, instance:flipkart.TestCases.LoginTest@293cde83] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- status -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:flipkart.TestCases.LoginTest@293cde83]" started-at="2023-01-09T17:15:09 IST" name="setup" finished-at="2023-01-09T17:15:53 IST" duration-ms="44883" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void flipkart.TestCases.LoginTest.ValidNumberLogin() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="ValidNumberLogin()[pri:2, instance:flipkart.TestCases.LoginTest@293cde83]" started-at="2023-01-09T17:15:53 IST" name="ValidNumberLogin" finished-at="2023-01-09T17:15:55 IST" duration-ms="1874" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [OTP is incorrect] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [OTP is incorrect] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at flipkart.Pages.LoginPage.assertValidNumberWithWrongOTP(LoginPage.java:104)
at flipkart.TestCases.LoginTest.ValidNumberLogin(LoginTest.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidNumberLogin -->
        <test-method is-config="true" signature="status(org.testng.ITestResult)[pri:0, instance:flipkart.TestCases.LoginTest@293cde83]" started-at="2023-01-09T17:15:55 IST" name="status" finished-at="2023-01-09T17:15:56 IST" duration-ms="526" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidNumberLogin status=FAILURE method=LoginTest.ValidNumberLogin()[pri:2, instance:flipkart.TestCases.LoginTest@293cde83] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- status -->
      </class> <!-- flipkart.TestCases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
